// Plantillas iniciales. El conector debe resolver optimization_goal, destino y action_type.
export const metaDashboards = [
  { objective: 'OUTCOME_AWARENESS', label: 'Reconocimiento', focus: 'Llegar a la audiencia adecuada', metrics: ['Alcance del período', 'Impresiones', 'Frecuencia', 'CPM'], chart: 'Impresiones y alcance por campaña', note: 'Alcance y frecuencia se consultan para el rango completo. No se suman entre días ni campañas.' },
  { objective: 'OUTCOME_TRAFFIC', label: 'Tráfico', focus: 'Visitas hacia el destino elegido', metrics: ['Clics en enlace', 'CTR de enlace', 'CPC de enlace', 'Visitas a página de destino'], chart: 'Evolución de visitas y costo por visita', note: 'Las visitas a página aplican a destinos web cuando están disponibles. Separar clics totales de clics en enlace.' },
  { objective: 'OUTCOME_ENGAGEMENT', label: 'Interacción', focus: 'La interacción que busca cada conjunto', metrics: ['Resultado optimizado', 'Costo por resultado', 'Inversión', 'Tendencia del resultado'], chart: 'Resultados por tipo: publicaciones, video o conversaciones', note: 'Separar conversaciones, interacciones y reproducciones según la optimización. No sumarlas como un mismo resultado.' },
  { objective: 'OUTCOME_LEADS', label: 'Clientes potenciales', focus: 'Captar oportunidades de contacto', metrics: ['Leads de Meta', 'CPL', 'Inversión', 'Tendencia de leads'], chart: 'Leads y CPL por formulario, web o mensajería', note: 'Seleccionar el evento de lead sin duplicar acciones. La calificación comercial se incorporará luego desde HubSpot.' },
  { objective: 'OUTCOME_SALES', label: 'Ventas', focus: 'Compras y valor atribuido', metrics: ['Compras atribuidas', 'Costo por compra', 'Valor de compra', 'ROAS'], chart: 'Compras y retorno por campaña y destino', note: 'Requiere eventos y valores de compra válidos. Otro evento optimizado no debe presentarse como venta.' },
  { objective: 'OUTCOME_APP_PROMOTION', label: 'Promoción de app', focus: 'Instalaciones y eventos de aplicación', metrics: ['Instalaciones', 'CPI', 'Eventos optimizados', 'Costo por evento'], chart: 'Instalaciones o eventos de app según la optimización', note: 'Depende de la medición de app y el evento elegido; sin eventos disponibles se muestra «Sin datos».' },
] as const;
