import { useEffect, useState, type CSSProperties } from 'react';
import type { Overview, Provider } from '../shared/contracts';
import { projects, providerLabels, type ProjectId } from '../shared/projects';
import { getOverview } from './lib/api';
import { historical, money, number, type ReportView } from './lib/historical';
import { SyncStatus } from './components/SyncStatus';

type View = 'summary' | Provider | 'connections';
export function App() {
  const [projectId, setProject] = useState<ProjectId>('pekin');
  const [view, setView] = useState<View>('summary');
  const [mode, setMode] = useState<'historical' | 'live'>('historical');
  const [objective, setObjective] = useState('leads');
  const [overview, setOverview] = useState<Overview | null>(null);
  const [error, setError] = useState('');
  const project = projects.find(item => item.id === projectId)!;
  const report = historical[projectId].find(item => item.id === objective) ?? historical[projectId][0];
  useEffect(() => {
    const controller = new AbortController(); setOverview(null); setError('');
    getOverview(projectId, controller.signal).then(result => { if (!controller.signal.aborted) setOverview(result); })
      .catch(() => { if (!controller.signal.aborted) setError('No se pudo consultar el estado de conexión.'); });
    return () => controller.abort();
  }, [projectId]);
  function selectProject(id: ProjectId) { setProject(id); setView('summary'); setObjective(historical[id][0].id); }
  return <div className="app" style={{'--project':project.accent} as CSSProperties}>
    <aside className="sidebar">
      <a href="#dashboard" className="agency"><img src="/brand/tictac-logo.png" alt="TicTac Agency Performance" /></a>
      <div className="workspace-label">KINKU <span>REPORTING STUDIO</span></div>
      <p className="nav-label">PROYECTOS</p>
      <nav className="project-nav" aria-label="Proyectos">{projects.map((item, i) => <button key={item.id} aria-pressed={projectId === item.id} onClick={() => selectProject(item.id)}><span className="project-dot" style={{background:item.accent}} />{item.name}<small>0{i+1}</small></button>)}</nav>
      <div className="sidebar-bottom"><span className="online-dot" /> Espacio del equipo<p>El sonido al éxito.</p><span className="sidebar-caption">TIC TAC / AGENCY PERFORMANCE</span></div>
    </aside>
    <div className="main-shell"><header className="topbar"><span>Kinku <span className="separator">/</span> {project.name} <span className="separator">/</span> Reporte de rendimiento</span><span className="team-badge">EQUIPO INTERNO <span className="avatar">TT</span></span></header>
      <main id="dashboard">
        <div className="page-heading"><div><p className="eyebrow">TIC TAC AGENCY × KINKU</p><h1>Todo el panorama.<br/><span>Una mejor decisión.</span></h1></div><div className="mode-controls"><label htmlFor="data-mode">FUENTE DEL REPORTE</label><select id="data-mode" value={mode} onChange={event => setMode(event.target.value as typeof mode)}><option value="historical">Informe histórico · septiembre 2026</option><option value="live">Conexiones en vivo · pendientes</option></select><span>America/Bogota · {mode === 'historical' ? '01 — 30 SEP, 2026' : 'Sin período sincronizado'}</span></div></div>
        <SyncStatus key={projectId} projectId={projectId} sync={overview?.projectId === projectId ? overview.sync : undefined}/>
        <section className="project-header"><div className={`project-logo ${projectId}`}><img src={project.image} alt={project.name}/></div><div><p className="eyebrow">PROYECTO / {project.name.toUpperCase()}</p><h2>{project.description}</h2></div><span className="project-counter">{String(projects.findIndex(item => item.id === projectId)+1).padStart(2,'0')}<small>/03</small></span></section>
        <nav className="view-nav" aria-label="Secciones del proyecto">{(['summary',...project.providers,'connections'] as View[]).map(item => <button key={item} onClick={() => setView(item)} aria-pressed={view === item}>{item === 'summary' ? 'Resumen ejecutivo' : item === 'connections' ? 'Conexiones' : providerLabels[item]}</button>)}</nav>
        {view !== 'connections' && <div className="source-notice"><span className="notice-dot"/><span>{mode === 'historical' ? 'INFORME HISTÓRICO · 30 SEP 2026' : 'DATOS EN VIVO · SIN CONECTAR'}</span><p>{mode === 'historical' ? 'Cifras del PowerPoint compartido. No representan el estado actual de las campañas.' : 'Los resultados aparecerán después de validar las conexiones de este proyecto.'}</p></div>}
        {view === 'connections' ? <section className="connections"><SectionTitle title="Las fuentes de este proyecto" kicker="CONEXIONES"/><p className="subtle">Cada proyecto mantiene sus cuentas y campañas por separado.</p>{error && <p role="alert">{error}</p>}<div className="connection-grid">{project.providers.map(provider => <article className="panel connection" key={provider}><div className="provider-icon">{provider === 'meta' ? '∞' : provider === 'google_ads' ? 'G' : 'H'}</div><h3>{providerLabels[provider]}</h3><p>{project.name} · {provider === 'hubspot' ? 'Gestión comercial' : 'Campañas y rendimiento'}</p><span className="pending">{error ? 'Estado no disponible' : overview?.projectId === projectId ? 'Pendiente de conexión' : 'Consultando estado…'}</span><div className="connection-bottom">Última sincronización <strong>Sin datos</strong></div></article>)}</div></section>
        : mode === 'live' ? <Empty title={`Conecta las fuentes de ${project.name}`} text="Aún no hay campañas activas verificadas. Los dashboards se organizarán por el objetivo y la optimización de las campañas que se importen." action={() => setView('connections')}/>
        : view === 'google_ads' ? projectId === 'pekin' ? <GoogleReport/> : <Empty title={`Google Ads de ${project.name}`} text="Esta fuente tiene su espacio independiente. El informe compartido no contiene cifras de Google Ads para este proyecto." action={() => setView('connections')}/>
        : view === 'hubspot' && projectId === 'pekin' ? <HubspotReport/>
        : <><div className="dashboard-heading"><SectionTitle kicker={view === 'meta' ? 'META ADS / OBJETIVOS' : 'RESUMEN / META ADS'} title="Resultados que importan"/><div className="objective-options" aria-label="Objetivos del reporte">{historical[projectId].map(item => <button key={item.id} aria-pressed={report.id === item.id} onClick={() => setObjective(item.id)}>{item.label}</button>)}</div></div><Metrics stats={report.stats}/><div className="dashboard-grid"><GoalChart report={report}/><SpendChart report={report}/></div><CampaignTable report={report}/><Executive note={report.note} source={`Fuente: diapositivas ${report.slides} · informe 30/09/2026`}/>{view === 'summary' && <div className="channel-links">{project.providers.filter(item => item !== 'meta').map(item => <button key={item} onClick={() => setView(item)}><span>{item === 'hubspot' ? 'Del lead a la oportunidad' : 'Otra perspectiva del rendimiento'}<strong>{providerLabels[item]}</strong></span><span>↗</span></button>)}</div>}</>}
        <footer><span>TIC TAC <strong>AGENCY PERFORMANCE</strong></span><span>{project.name} · {mode === 'historical' ? 'Referencia septiembre 2026' : 'Pendiente de sincronización'}</span></footer>
      </main>
    </div>
  </div>;
}
function SectionTitle({title,kicker}:{title:string;kicker:string}) { return <div><p className="eyebrow">{kicker}</p><h2>{title}</h2></div>; }
function Metrics({stats}:{stats: readonly [string,string,string][]}) { return <div className="metrics">{stats.map(([label,value,hint],i) => <article className={`metric ${i===3?'highlight':''}`} key={label}><div className="metric-label">{label}<span>↗</span></div><strong>{value}</strong><small>{hint}</small></article>)}</div>; }
function GoalChart({report}:{report:ReportView}) { const max=Math.max(120,...report.rows.map(row => row.result/row.target*100));return <section className="panel"><div className="panel-heading"><h3>Resultados vs. meta</h3><span className="mini-tag">{report.unit}</span></div><p className="subtle">El objetivo marca el punto de referencia.</p><div className="goal-chart">{report.rows.map(row => <div className="goal-row" key={row.name}><div><span>{row.name}</span><strong>{number(row.result/row.target*100)}%</strong></div><div className="goal-track"><div className="goal-fill" style={{width:`${row.result/row.target*100/max*100}%`}}/><span className="target-marker" style={{left:`${100/max*100}%`}}/></div><small>{number(row.result)} resultados <span>Meta: {number(row.target)}</span></small></div>)}</div><div className="chart-legend"><span><i/>Resultado del período</span><span><b/>Meta del informe</span></div></section>; }
function SpendChart({report}:{report:ReportView}) { const total=report.rows.reduce((sum,row)=>sum+row.spend,0);return <section className="panel"><div className="panel-heading"><h3>Distribución de inversión</h3><span className="mini-tag">COP</span></div><div className="spend-total"><strong>{money(total)}</strong><span>Inversión · {report.label.toLowerCase()}</span></div><div className="allocation">{report.rows.map((row,i)=><div key={row.name} style={{width:`${row.spend/total*100}%`,opacity:1-i*.4}} title={`${row.name}: ${money(row.spend)}`}/>)}</div>{report.rows.map((row,i)=><div className="spend-row" key={row.name}><span><i style={{opacity:1-i*.4}}/>{row.name}</span><strong>{money(row.spend)}</strong></div>)}</section>; }
function CampaignTable({report}:{report:ReportView}) { return <section className="panel table-panel"><div className="panel-heading"><h3>Detalle por línea de campaña</h3><span className="mini-tag">CORTE HISTÓRICO</span></div><div className="table-scroll"><table><thead><tr><th>Línea</th><th>Resultado</th><th>Meta</th><th>Inversión</th><th>Costo / resultado</th></tr></thead><tbody>{report.rows.map(row=><tr key={row.name}><td><span className="table-dot"/>{row.name}</td><td>{number(row.result)} <small>{row.unit}</small></td><td>{number(row.target)}</td><td>{money(row.spend)}</td><td>{money(row.spend/row.result)}</td></tr>)}</tbody></table></div><p className="table-note">Las líneas agrupan campañas según el informe. Su estado activo actual está pendiente de verificar.</p></section>; }
function Executive({note,source}:{note:string;source:string}) { return <section className="executive"><div className="executive-icon">✳</div><div><p className="eyebrow">LECTURA EJECUTIVA / INFORME HISTÓRICO</p><p>{note}</p><small>{source}</small></div></section>; }
function Empty({title,text,action}:{title:string;text:string;action:()=>void}) { return <section className="panel empty"><span>◎</span><h2>{title}</h2><p>{text}</p><button className="primary" onClick={action}>Ver conexiones ↗</button></section>; }
function GoogleReport() {return <><SectionTitle title="Google Ads · Pekín" kicker="CONVERSIONES Y EFICIENCIA"/><Metrics stats={[["Conversiones","97","Google Ads general"],["Inversión","≈ $636 mil","COP · dato aproximado"],["Clics","585","Rango del informe"],["CPA","≈ $6,6 mil","COP · por conversión"]]}/><section className="panel"><h3>Aporte por tipo de campaña</h3><div className="comparison-bars">{[['PMAX',78],['Search',19]].map(([label,value])=><div key={label}><span>{label}</span><div><i style={{width:`${Number(value)/97*100}%`}}/></div><strong>{value}</strong></div>)}</div><p className="subtle">97 conversiones totales. La meta de 35 leads corresponde solo a PMAX y requiere validar equivalencia.</p></section><Executive note="PMAX aporta 78 conversiones. El total de Google Ads incluye Search; no debe compararse con la meta exclusiva de PMAX. El informe muestra PMAX detenida, por lo que este histórico no acredita campañas activas hoy." source="Fuente: diapositivas 12–13 · informe 30/09/2026"/></>;}
function HubspotReport() {const stages:[string,number][]=[['Lead',106],['MQL',94],['SQL',19],['Clientes',4]];return <><SectionTitle title="Del contacto a la oportunidad" kicker="HUBSPOT / EXCLUSIVO PEKÍN"/><Metrics stats={[["Contactos","223","Total del embudo"],["MQL","94","Calificados por marketing"],["SQL","19","Calificados para ventas"],["Clientes","4","Estado en el corte histórico"]]}/><div className="dashboard-grid"><section className="panel"><h3>Ciclo de vida de los contactos</h3><div className="comparison-bars">{stages.map(([label,value])=><div key={label}><span>{label}</span><div><i style={{width:`${value/106*100}%`}}/></div><strong>{value}</strong></div>)}</div><p className="subtle">Distribución de estados al corte; no es una tasa de conversión entre etapas.</p></section><section className="panel"><h3>Estado de seguimiento</h3>{[['Marcar de nuevo',77],['No útil',67],['Seguimiento',38],['Leads calientes',27],['Citas programadas',10],['Citas efectivas',4]].map(([label,value])=><div className="spend-row" key={label}><span>{label}</span><strong>{value}</strong></div>)}</section></div><Executive note="El informe concentra 200 contactos en Lead y MQL. La prioridad documentada es avanzar la gestión comercial y retomar los contactos pendientes. Estos contactos no se suman a los leads de pauta como resultados adicionales." source="Fuente: diapositivas 14–15 · informe 30/09/2026"/></>;}
